# Create a Status named 'Required' that reports the observed conclusion of all
# WorkflowRuns with a name matching `/required/i` on the same `head_sha` as the
# observed WorkflowRun.
name: Required

on:
  workflow_run:
    workflows:
      - Build Devcontainer - Required
      - Build Docker Image - Required
      - Frontend Code Quality Check - Required
      - Unit Test - Required
      - Test Charts - Required
    types:
      - completed

jobs:
  success:
    if: github.event.workflow_run.event == 'pull_request'
    name: Create appropriate status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          STATUS_NAME: Required
        with:
          retries: 2
          script: |
            const script = require('./.github/workflows/required.js')
            await script({github, context})
